robotnik_base_controller:
  type: ackermann_drive_controller/AckermannDriveController
  traction:
    front_right:
      joint_name: robot_right_front_axle
      max_speed: 20.0 # rad/s
    front_left:
      joint_name: robot_left_front_axle
      max_speed: 20.0 # rad/s
    back_right:
      joint_name: robot_right_rear_axle
      max_speed: 20.0 # rad/s
    back_left:
      joint_name: robot_left_rear_axle
      max_speed: 20.0 # rad/s
  steer:
    front_right:
      joint_name: robot_right_steering_joint
      min_angle: -0.7 # rads
      max_angle: 0.6
    front_left:
      joint_name: robot_left_steering_joint
      min_angle: -0.6 # rads
      max_angle: 0.7
  linear_speed_limit: 10
  linear_acceleration_limit: 1.0
  angular_speed_limit: 2.0
  angular_acceleration_limit: 2.0 
  odom_frame: robot_odom
  robot_base_frame: robot_base_footprint
  odom_broadcast_tf: true
  odom_topic: odom
  command_topic: cmd_vel
  applied_command_topic: applied_cmd_vel
  wheel_base: 1.630
  track_width: 1.050
  wheel_diameter: 0.440 # 0.185... calibrated, 0.186 from cad
  cmd_watchdog_duration: 0.2
  odom_publish_frequency: 100

joint_read_state_controller:
  type: joint_state_controller/JointStateController 
  publish_rate: 100.0

joint_read_command_controller:
  type: joint_read_command_controller/JointReadCommandController

#joint_pan_position_controller:
#  type: velocity_controllers/JointPositionController
#  joint: front_ptz_camera_pan_joint
#  pid: {p: 100.0, i: 0.01, d: 10.0}

#joint_tilt_position_controller:
#  type: velocity_controllers/JointPositionController
#  joint: front_ptz_camera_tilt_joint
#  pid: {p: 100.0, i: 0.01, d: 10.0}

#elevator_controller:
#  type: position_controllers/JointPositionController
#  joint: elevator_joint
